#! /bin/bash

ip netns add myns

ip link add veth0 type veth peer name veth1

ip link set veth0 master docker0
ip link set veth0 up
ip link set docker0 up

ip link set veth1 netns myns

ip netns exec myns ip addr add 172.17.0.2/16 dev veth1
ip netns exec myns ip link set lo up
ip netns exec myns ip link set veth1 up
ip netns exec myns ip route add default via 172.17.0.1

mkdir -p /tmp/myns_etc
bash -c "echo 'nameserver 8.8.8.8' > /tmp/myns_etc/resolv.conf"

mkdir /sys/fs/cgroup/myns

bash -c "echo '20000 100000' > /sys/fs/cgroup/myns/cpu.max"


ip netns exec myns unshare --mount --pid --ipc --uts --fork --mount-proc bash -c '
mount --bind /tmp/myns_etc/resolv.conf /etc/resolv.conf
exec bash
'

rmdir /sys/fs/cgroup/myns

ip netns delete myns

